version: "3.3"

services:
  producer:
    build:
      context: local
    command: ["python3", "main_producer.py", "worker"]
    restart: always
    depends_on:
      - kafka

  consumer:
    build:
      context: local
    command: ["python3", "main_consumer.py", "worker"]
    restart: always
    depends_on:
      - kafka

  zookeeper:
    # https://hub.docker.com/r/wurstmeister/zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    # https://hub.docker.com/r/wurstmeister/kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS: "hello:1:1,goodbye:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
